### ISSUE TITLE
Bump compat for CUDA v3?

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/AMGX.jl#16]
Can we bump the compat requirements to allow CUDA v3?

https://github.com/JuliaGPU/AMGX.jl/blob/e7ac5aaf3d141425dcb1f5ebd2b203901f6e5856/Project.toml#L16

(cc @Elise-palethorpe)

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/General/pull/63818
