### ISSUE TITLE
Changing config parameters after solver creation

### ISSUE THREAD

**Issue by elise-palethorpe** [JuliaGPU/AMGX.jl#19]
Is there a way to change config parameters (particularly the tolerance) after a solver is created without reinitializing the solver? 

I can initialize a solver with a very high tolerance following the README:
```julia
using AMGX
AMGX.initialize()
AMGX.initialize_plugins()

config = AMGX.Config(Dict("monitor_residual" => 1, "max_iters" => 10, "tolerance" => 10, "store_res_history" => 1));
resources = AMGX.Resources(config)
v = AMGX.AMGXVector(resources, AMGX.dDDI)
AMGX.upload!(v, [1.0, 2.0, 3.0])

matrix = AMGX.AMGXMatrix(resources, AMGX.dDDI)
AMGX.upload!(matrix,
    Cint[0, 1, 3], # row_ptrs
    Cint[1, 0, 1], # col_indices
    [1.0, 2.0, 3.0] # data
)
solver = AMGX.Solver(resources, AMGX.dDDI, config)
x = AMGX.AMGXVector(resources, AMGX.dDDI)
AMGX.set_zero!(x, 3)
AMGX.setup!(solver, matrix)
AMGX.solve!(x, solver, v)
Vector(x)
```
outputs
```julia
3-element Vector{Float64}:
 0.0
 0.0
 0.0
```
but then when I tried giving a new config with an updated tolerance

```julia
config2 = AMGX.Config(Dict("monitor_residual" => 1, "max_iters" => 10, "tolerance" => 1e-8, "store_res_history" => 1))
solver.config = config2
solver.resources = AMGX.Resources(config2)
AMGX.solve!(x, solver, v)
Vector(x)
```

it again outputs
```julia
julia> Vector(x)
3-element Vector{Float64}:
 0.0
 0.0
 0.0
```

which implies that the new tolerance is not seen by the solver?

cc @navidcy @glwagner

**Comment by KristofferC** [comment]
This is from the AMGX documentation (page 64):

> There is no way to change the Config on a Solver once it is created - instead, you must destroy the Solver and create a new one with the modified Config settings.

So I think that is what you need to do.

**Comment by navidcy** [comment]
perhaps we close this?
