### ISSUE TITLE
Support for CUDA v4?

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/AMGX.jl#26]
Can we add a compat entry for CUDA v4 and publish a new AMGX release?

https://github.com/JuliaGPU/AMGX.jl/blob/0b277233459c8535670fe635cdafa29da595d155/Project.toml#L16

**Comment by vchuravy** [comment]
Also started building AMGX with the new CUDA platform but I don't quite know what I am doing there https://github.com/JuliaPackaging/Yggdrasil/pull/6202

**Comment by KristofferC** [comment]
Did you check that this package works well with CUDA.jl@v4?
